### ISSUE TITLE
 java.lang.LinkError: class not found: java/lang/Class

### ISSUE THREAD

**Issue by 0xdoraemon** [imkiva/KiVM#2]
你好，我今天调试过程出现了这个问题，请问这是什么原因导致的呢 ？
![3cf51753-47f9-4668-92da-8a1eed132283](https://user-images.githubusercontent.com/16839929/50952058-2e1bfe00-14ea-11e9-8bd6-d87a09108316.png)

**Comment by imkiva** [comment]
我一直是在 IDE 里运行的，但是我在终端下可以正常工作，无法复现这个问题。
可否提供一下 cmake 时的输出呢？我猜是因为没有找到 `libzip` 所以没有开启从 jar 中加载 class 文件的功能

![image](https://user-images.githubusercontent.com/9902643/50979568-b8d41b80-1531-11e9-8bf7-3545380bb882.png)

**Comment by imkiva** [comment]
试试 `brew install libzip`

**Comment by 0xdoraemon** [comment]
你好，下面是cmake的输出信息，还有libzip的信息。我试了还是不可以。
![57457c97-d656-4108-a8c9-b73e94dbbff0](https://user-images.githubusercontent.com/16839929/51012024-fff3f800-1595-11e9-8fe1-0a8c8745b67e.png)
![73f6112e-46a2-4348-b4bc-add4c7e1a28e](https://user-images.githubusercontent.com/16839929/51012029-097d6000-1596-11e9-8491-2c8bcc399a45.png)

**Comment by imkiva** [comment]
你好，可否看一下执行 `cmake` 的时候的输出，就是包含了类似下面信息的
![image](https://user-images.githubusercontent.com/9902643/51042419-37df5780-15f7-11e9-88ac-1827b713e41c.png)

看看有没有 `Jar class loading enabled` 这样的输出

**Comment by imkiva** [comment]
很抱歉每天只能到这时候才能回复 issue，希望谅解 😄

**Comment by 0xdoraemon** [comment]
客气了，你能帮忙解决问题我感谢都来不及呢。问题我已经找到了，是缺少Java for OS X 2017-001
这个，我安装后就可以了。非常感谢

**Comment by imkiva** [comment]
好的，那我就close了

**Comment by cookieli** [comment]
我在ubuntu18.04下也出现了该问题
