### ISSUE TITLE
error: redefinition of 'struct kivm::PrimitiveHelper<long int>'

### ISSUE THREAD

**Issue by ColumPaget** [imkiva/KiVM#3]
Hiya,

Building on a linux-from-scratch system I get the below error.

regards,

Colum

[ 18%] Building CXX object CMakeFiles/kivm.dir/src/kivm/bytecode/interpreter.cpp.o
In file included from /home/source/development-java/KiVM-0.2.0/src/kivm/oop/instanceKlass.cpp:6:
/home/source/development-java/KiVM-0.2.0/include/kivm/oop/primitiveOop.h:29:12: error: redefinition of 'struct kivm::PrimitiveHelper<long int>'
     struct PrimitiveHelper<long> {
            ^~~~~~~~~~~~~~~~~~~~~
/home/source/development-java/KiVM-0.2.0/include/kivm/oop/primitiveOop.h:15:12: note: previous definition of 'struct kivm::PrimitiveHelper<long int>'
     struct PrimitiveHelper<jint> {
            ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/source/development-java/KiVM-0.2.0/src/kivm/bytecode/interpreter.cpp:10:
/home/source/development-java/KiVM-0.2.0/include/kivm/oop/primitiveOop.h:29:12: error: redefinition of 'struct kivm::PrimitiveHelper<long int>'
     struct PrimitiveHelper<long> {
            ^~~~~~~~~~~~~~~~~~~~~
/home/source/development-java/KiVM-0.2.0/include/kivm/oop/primitiveOop.h:15:12: note: previous definition of 'struct kivm::PrimitiveHelper<long int>'
     struct PrimitiveHelper<jint> {

**Comment by imkiva** [comment]
This has been fixed in master branch. Could you have a try? :)
