### ISSUE TITLE
What is mirrorOop and mirrorKlass in oop folder?

### ISSUE THREAD

**Issue by cookieli** [imkiva/KiVM#5]

**Comment by imkiva** [comment]
They are `java.lang.Class` and its instance.

**Comment by cookieli** [comment]
> They are `java.lang.Class` and its instance.

Thanks, it is really helpful.

**Comment by cookieli** [comment]
mirrorKlass是不是代表jvm中的原生类?,不好意思相关资料不是特别好找,
