### ISSUE TITLE
What is "Hotspot In Action"?

### ISSUE THREAD

**Issue by Dragonchu** [imkiva/KiVM#9]
Hello, imkiva.

KiVM is inspired by Hotspot In Action.

Is "Hotspot In Action" a book or a blog? I can't find any information about it on the internet.

I am very interested in "Hotspot In Action".

**Comment by imkiva** [comment]
If I recall correctly it is a Chinese book called [《HotSpot实战》](https://book.douban.com/subject/25847620/).

This book is a good reference for HotSpot source code, and it gives you a very basic understanding of the whole JVM framework.

**Comment by Dragonchu** [comment]
Thank you🙏🏻
